source 'https://github.com/CocoaPods/Specs.git'

target 'ABToolKit', :exclusive => true do
  pod "ABToolKit", :path => "../"
  use_frameworks!
end

target 'Tests', :exclusive => true do
  pod "ABToolKit", :path => "../"
  use_frameworks!
  pod 'FBSnapshotTestCase'
end
